/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Coordenada;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import logica.Calculadora_1;

/**
 *
 * @author Gaia F. Braccia
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboxDe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cboxA = new javax.swing.JComboBox<>();
        txtAngulo1Res = new javax.swing.JTextField();
        txtAngulo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAngulo2Res = new javax.swing.JTextField();
        txtAngulo2 = new javax.swing.JTextField();
        butVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labAngulo1 = new javax.swing.JLabel();
        labAngulo2 = new javax.swing.JLabel();
        labAngulo1Res = new javax.swing.JLabel();
        labAngulo2Res = new javax.swing.JLabel();
        butCalcular = new javax.swing.JButton();
        txtLatitud = new javax.swing.JTextField();
        labLatitud = new javax.swing.JLabel();
        butLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboxDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horizontales", "Ecuatoriales Horarias", "Ecuatoriales Absolutas", "Eclipticas" }));
        cboxDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxDeActionPerformed(evt);
            }
        });
        jPanel1.add(cboxDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 141, 30));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("De:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        cboxA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horizontales", "Ecuatoriales Horarias", "Ecuatoriales Absolutas", "Eclipticas" }));
        cboxA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxAActionPerformed(evt);
            }
        });
        jPanel1.add(cboxA, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 141, 30));

        txtAngulo1Res.setEditable(false);
        jPanel1.add(txtAngulo1Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 141, 50));

        txtAngulo1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        txtAngulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngulo1ActionPerformed(evt);
            }
        });
        txtAngulo1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAngulo1KeyTyped(evt);
            }
        });
        jPanel1.add(txtAngulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 141, 50));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("A:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculadora");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 350, -1));

        txtAngulo2Res.setEditable(false);
        txtAngulo2Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngulo2ResActionPerformed(evt);
            }
        });
        jPanel1.add(txtAngulo2Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 141, 50));

        txtAngulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAngulo2ActionPerformed(evt);
            }
        });
        txtAngulo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAngulo2KeyTyped(evt);
            }
        });
        jPanel1.add(txtAngulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 141, 50));

        butVolver.setBackground(new java.awt.Color(0, 0, 51));
        butVolver.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butVolver.setForeground(new java.awt.Color(255, 255, 255));
        butVolver.setText("Volver");
        butVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVolverActionPerformed(evt);
            }
        });
        jPanel1.add(butVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 110, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        labAngulo1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        labAngulo1.setForeground(new java.awt.Color(255, 255, 255));
        labAngulo1.setText("Altura(a):");
        jPanel1.add(labAngulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        labAngulo2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        labAngulo2.setForeground(new java.awt.Color(255, 255, 255));
        labAngulo2.setText("Acimut(A):");
        jPanel1.add(labAngulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 30));

        labAngulo1Res.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        labAngulo1Res.setForeground(new java.awt.Color(255, 255, 255));
        labAngulo1Res.setText("Altura(a):");
        jPanel1.add(labAngulo1Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));

        labAngulo2Res.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        labAngulo2Res.setForeground(new java.awt.Color(255, 255, 255));
        labAngulo2Res.setText("Acimut(A):");
        jPanel1.add(labAngulo2Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 30));

        butCalcular.setBackground(new java.awt.Color(0, 0, 51));
        butCalcular.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butCalcular.setForeground(new java.awt.Color(255, 255, 255));
        butCalcular.setText("Calcular");
        butCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(butCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 110, -1));

        txtLatitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLatitudActionPerformed(evt);
            }
        });
        jPanel1.add(txtLatitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 60, -1));

        labLatitud.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        labLatitud.setForeground(new java.awt.Color(255, 255, 255));
        labLatitud.setText("Latitud:");
        jPanel1.add(labLatitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 40));

        butLimpiar.setBackground(new java.awt.Color(0, 0, 51));
        butLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        butLimpiar.setText("Limpiar");
        butLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(butLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/astronomia-constelaciones.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -10, 750, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAngulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngulo1ActionPerformed

    private void txtAngulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngulo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngulo2ActionPerformed

    private void butVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu = new MenuPrincipal();

        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_butVolverActionPerformed

    private void butCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCalcularActionPerformed
        // TODO add your handling code here:
        if (txtAngulo1.getText().isEmpty() || txtAngulo2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No ha ingresado ningun valor", "Error", JOptionPane.ERROR_MESSAGE);
        }

        double ang1 = Double.parseDouble(txtAngulo1.getText());
        double ang2 = Double.parseDouble(txtAngulo2.getText());
        Coordenada cor = new Coordenada(ang1, ang2);
        Calculadora_1 c = new Calculadora_1(cor);
        String op = (String) cboxDe.getSelectedItem();
        String op1 = (String) cboxA.getSelectedItem();
        if (op.equals(op1)) {
            txtAngulo1Res.setText(txtAngulo1.getText());
            txtAngulo2Res.setText(txtAngulo2.getText());
        } else {

            if (op.equals("Horizontales") && op1.equals("Ecuatoriales Horarias")) {
                cor = c.deHorizontalesAEcuatorialesHorarias(Double.parseDouble(txtLatitud.getText()), cor);
                this.setRespuesta(cor);

            } else if (op.equals("Ecuatoriales Horarias") && op1.equals("Horizontales")) {
                this.setRespuesta(cor);

            } else if (op.equals("Ecuatoriales Horarias") && op1.equals("Ecuatoriales Absolutas")) {
                cor = c.deEcuatorialesHorariasAAbsolutas(Double.parseDouble(txtLatitud.getText()), cor);
                this.setRespuesta(cor);

            } else if (op.equals("Ecuatoriales Absolutas") && op1.equals("Ecuatoriales Horarias")) {
                cor = c.deAbsolutasAEcuatorialesHorarias(Double.parseDouble(txtLatitud.getText()), cor);
                this.setRespuesta(cor);

            } else if (op.equals("Ecuatoriales Absolutas") && op1.equals("Eclipticas")) {
                cor = c.deAbsolutasAEclipticas(cor);
                this.setRespuesta(cor);

            } else if (op.equals("Eclipticas") && op1.equals("Ecuatoriales Absolutas")) {
                cor = c.deEcplipticasAAbsolutas(cor);
                this.setRespuesta(cor);
            } else {
                JOptionPane.showMessageDialog(this, "Esta transformacion no se puede realizar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_butCalcularActionPerformed
    public void setRespuesta(Coordenada cor) {
        txtAngulo1Res.setText(String.valueOf(cor.getAngulo1()));
        txtAngulo2Res.setText(String.valueOf(cor.getAngulo2()));
    }

    private void cboxDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxDeActionPerformed
        // TODO add your handling code here:
        String op = (String) cboxDe.getSelectedItem();
        cambiarLab1(op);
        txtAngulo1.setText("");
        txtAngulo2.setText("");
        txtLatitud.setText("");
    }//GEN-LAST:event_cboxDeActionPerformed

    private void cboxAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAActionPerformed
        // TODO add your handling code here:
        String op = (String) cboxA.getSelectedItem();
        cambiarLab2(op);
         txtAngulo1Res.setText("");
        txtAngulo2Res.setText("");
    }//GEN-LAST:event_cboxAActionPerformed

    private void txtLatitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLatitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLatitudActionPerformed

    private void txtAngulo2ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAngulo2ResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAngulo2ResActionPerformed

    private void butLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarActionPerformed
        // TODO add your handling code here:
        txtAngulo1.setText("");
        txtAngulo2.setText("");
        txtAngulo1Res.setText("");
        txtAngulo2Res.setText("");
        txtLatitud.setText("");
    }//GEN-LAST:event_butLimpiarActionPerformed

    private void txtAngulo1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngulo1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtAngulo1KeyTyped

    private void txtAngulo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAngulo2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtAngulo2KeyTyped

    public void cambiarLab1(String comb) {
        String op = comb;
        switch (op) {
            case "Horizontales":
                labAngulo1.setText("Altura(a):");
                labAngulo2.setText("Acimut(A):");
                labLatitud.setText("Latitud:");
                break;

            case "Ecuatoriales Horarias":
                labAngulo1.setText("Angulo Hoario(H):");
                labAngulo2.setText("Declinacion(d):");
                labLatitud.setText("Latitud:");
                break;

            case "Ecuatoriales Absolutas":
                labAngulo1.setText("Asension Recta(a):");
                labAngulo2.setText("Declinacion(d):");
                break;

            case "Eclipticas":
                labAngulo1.setText("Longitud Celeste(y):");
                labAngulo2.setText("Latitud Celeste(b):");
                break;

        }
    }

    public void cambiarLab2(String comb) {
        String op = comb;
        switch (op) {
            case "Horizontales":
                labAngulo1Res.setText("Altura(a):");
                labAngulo2Res.setText("Acimut(A):");
                
                break;

            case "Ecuatoriales Horarias":
                labAngulo1Res.setText("Angulo Hoario(H):");
                labAngulo2Res.setText("Declinacion(A):");
                
                break;

            case "Ecuatoriales Absolutas":
                labAngulo1Res.setText("Asension Recta(H):");
                labAngulo2Res.setText("Declinacion(A):");
                break;

            case "Eclipticas":
                labAngulo1Res.setText("Longitud Celeste(H):");
                labAngulo2Res.setText("Latitud Celeste(A):");
                break;

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCalcular;
    private javax.swing.JButton butLimpiar;
    private javax.swing.JButton butVolver;
    private javax.swing.JComboBox<String> cboxA;
    private javax.swing.JComboBox<String> cboxDe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAngulo1;
    private javax.swing.JLabel labAngulo1Res;
    private javax.swing.JLabel labAngulo2;
    private javax.swing.JLabel labAngulo2Res;
    private javax.swing.JLabel labLatitud;
    private javax.swing.JTextField txtAngulo1;
    private javax.swing.JTextField txtAngulo1Res;
    private javax.swing.JTextField txtAngulo2;
    private javax.swing.JTextField txtAngulo2Res;
    private javax.swing.JTextField txtLatitud;
    // End of variables declaration//GEN-END:variables

}
