/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JCalendar;
import data.Evento;
import data.ObjetoCeleste;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Univerzoom;
/**
 *
 * @author nicom
 */
public class VentanaCalendario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCalendario
     */
   static  ArrayList<Evento> listaEventos = new ArrayList<>();
    
    
    
    public VentanaCalendario() {
        initComponents();
        setSize(700,500);
          
        setLocationRelativeTo(null); 
         cargarInfo(listaEventos);
         
         ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon imgFondo= new ImageIcon(this.getClass().getResource("/img/u3.jpg"));
        imgFondo= new ImageIcon(imgFondo.getImage().getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH));
        
        JLabel fondo= new JLabel();
        fondo.setIcon(imgFondo);
        
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0, imgFondo.getIconWidth(), imgFondo.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        butEliminar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        txtHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNuevoEvento = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        butMostar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        butVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jCalendar1.setDate(new java.util.Date(1563051021000L));
        jCalendar1.setOpaque(false);
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(10, 99, 359, 310);
        jCalendar1.getAccessibleContext().setAccessibleName("");

        butEliminar.setText("Eliminar evento");
        butEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        butEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(butEliminar);
        butEliminar.setBounds(410, 340, 100, 40);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear evento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);

        btnCrear.setBackground(new java.awt.Color(0, 0, 51));
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora (hh:mm:ss)");

        txtNuevoEvento.setColumns(20);
        txtNuevoEvento.setRows(5);
        jScrollPane1.setViewportView(txtNuevoEvento);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Evento:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(379, 99, 285, 229);

        butMostar.setBackground(new java.awt.Color(0, 0, 51));
        butMostar.setForeground(new java.awt.Color(255, 255, 255));
        butMostar.setText("Mostar");
        butMostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butMostarActionPerformed(evt);
            }
        });
        getContentPane().add(butMostar);
        butMostar.setBounds(550, 340, 90, 40);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calendario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(167, 22, 350, 59);

        butVolver.setBackground(new java.awt.Color(0, 0, 51));
        butVolver.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butVolver.setForeground(new java.awt.Color(255, 255, 255));
        butVolver.setText("Volver");
        butVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVolverActionPerformed(evt);
            }
        });
        getContentPane().add(butVolver);
        butVolver.setBounds(554, 11, 110, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butMostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butMostarActionPerformed
        ArrayList<Evento> eventosF = new ArrayList<>();
        
        Date date = jCalendar1.getDate();
        String fecha = formatearFecha(date);
        for(int i=0; i<listaEventos.size();i++){
            if(listaEventos.get(i).getFecha().equals(fecha)){
                eventosF.add(listaEventos.get(i));
            }
        }
        for(int i=0; i<eventosF.size();i++){
            System.out.println(eventosF.get(i).getEvento());
        }
        if(eventosF.size()==0){
           JOptionPane.showMessageDialog(null, "No hay ningún evento en esta fecha","Eventos",JOptionPane.INFORMATION_MESSAGE);
        }else{
        String listaEventos = imprimirEventos(eventosF);
        JOptionPane.showMessageDialog(null, listaEventos,"Eventos",JOptionPane.PLAIN_MESSAGE);
        }
        
    }//GEN-LAST:event_butMostarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String hora = txtHora.getText().equals("") ?"00:00:00":txtHora.getText();
        String even = txtNuevoEvento.getText();
        Date date = jCalendar1.getDate();
        String fecha = formatearFecha(date);
        
        Evento e1 = new Evento(fecha,hora, even);
        listaEventos.add(e1);
        guardarInfo(e1);
        JOptionPane.showMessageDialog(null, "Evento Creado exitosamente"+"\nHora: "+e1.getHora()+"  "
                + "    Evento: "+e1.getEvento(),"Evento",JOptionPane.INFORMATION_MESSAGE);
        
        txtHora.setText("");
        txtNuevoEvento.setText("");
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void butVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVolverActionPerformed
        // TODO add your handling code here:
        MenuPrincipal menu= new MenuPrincipal();

        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_butVolverActionPerformed

    private void butEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butEliminarActionPerformed
        VentanaBorrarEvento vb = new VentanaBorrarEvento();
        vb.setVisible(true);
    }//GEN-LAST:event_butEliminarActionPerformed
    
    private static String imprimirEventos(ArrayList<Evento> list){
        String listaE ="";
        
        for(Evento e:list){
            listaE+="Hora: "+e.getHora()+"\nEvento: "+e.getEvento()+"\n";
        }
        return listaE;
    }
    
    private static String formatearFecha(Date date){
        long d = date.getTime();
        java.sql.Date fecha = new java.sql.Date(d);
        
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String strDate = dateFormat.format(fecha);
        
        return strDate;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalendario().setVisible(true);
            }
        });
       
    
    }
    
    private static void cargarInfo(ArrayList<Evento> listaEventos) {
        try {
            File file = new File("Eventos.txt");

            FileReader fileReader = new FileReader(file);
            BufferedReader reader = new BufferedReader(fileReader);

            String line = null;

            while ((line = reader.readLine()) != null) {
                String[] ArrEventos = line.split(",");
                Evento ev = new Evento(ArrEventos[0], ArrEventos[1], ArrEventos[2], Integer.parseInt(ArrEventos[3]));
                listaEventos.add(ev);
            }
            reader.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private static void guardarInfo(Evento evento) {
        FileWriter writer = null;

        try {
            writer = new FileWriter("Eventos.txt",true);

            writer.write(evento.toString());
            writer.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton butEliminar;
    private javax.swing.JButton butMostar;
    private javax.swing.JButton butVolver;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextArea txtNuevoEvento;
    // End of variables declaration//GEN-END:variables
    

}

