/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Usuario;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logica.Conexion;
import logica.ReguladorUsuario;
import logica.Univerzoom;

/**
 *
 * @author Gaia F. Braccia
 */
public class VentanaInicioSesion extends javax.swing.JFrame {
    
    private static Usuario u= new Usuario();
    /**
     * Creates new form VentanaInicioSesion
     */
    public VentanaInicioSesion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
    }

    

    public static Usuario getU() {
        return u;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        butIniciar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        butRegistar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Univerzoom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 330, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("El universo en tus bolsillos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, 30));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, 30));
        getContentPane().add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 110, -1));

        butIniciar.setBackground(new java.awt.Color(0, 0, 51));
        butIniciar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butIniciar.setForeground(new java.awt.Color(255, 255, 255));
        butIniciar.setText("Iniciar sesión");
        butIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butIniciarMouseClicked(evt);
            }
        });
        getContentPane().add(butIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 110, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("¿No tienes una cuenta?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        butRegistar.setBackground(new java.awt.Color(0, 0, 51));
        butRegistar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butRegistar.setForeground(new java.awt.Color(255, 255, 255));
        butRegistar.setText("Regístrate");
        butRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butRegistarActionPerformed(evt);
            }
        });
        getContentPane().add(butRegistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 110, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("lo desconocido. Ahora es tu turno!");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("El universo es un lugar vasto y misterioso. ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Durante milenios, los seres humanos que ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("cosmos, se asombraron y fascinaron por ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("miraban al cielo como nuestra ventana al ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/u7.png"))); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 480, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butRegistarActionPerformed
        // TODO add your handling code here:
      new VentanaInicioSesion().setVisible(false);
      VentanaRegistro registro=new VentanaRegistro();
      
      registro.setVisible(true);
      dispose();
    }//GEN-LAST:event_butRegistarActionPerformed

    private void butIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butIniciarMouseClicked
        // TODO add your handling code here:
        
        Conexion men1 = new Conexion();
         Conexion con = new Conexion();
         
        try{ 
            String usuario=txtUsuario.getText();
            String cont= new String(txtContraseña.getPassword());
           
           Statement comando=con.getConnection().createStatement();
           //comando.executeQuery("SELECT * FROM usuarios where usuario='"+usuario+"' and contraseña='"+cont+"'");
           //String a="SELECT * FROM usuarios where usuario='"+usuario+"' and contraseña='"+cont+"'";
           ResultSet rs =comando.executeQuery("SELECT * FROM usuarios where usuario='"+usuario+"' and contraseña='"+cont+"'"); 
           if(rs.next()){
              
               
                
               
               String nombre=rs.getString(2);
               String apellido=(rs.getString(3));
               String correo=(rs.getString(4));
               int edad=Integer.parseInt(rs.getString(5));
               int ced=Integer.parseInt(rs.getString(1));
               u.cambiarDatos(usuario,ced, nombre, apellido, edad, correo, cont);
               
               
               
              
             MenuPrincipal menu= new MenuPrincipal();
             menu.setVisible(true);
             dispose();
               System.out.println("prubea");
           }else{
               JOptionPane.showMessageDialog( this, "Usuaio y/o contraseña invalidos","Error",JOptionPane.ERROR_MESSAGE);
           }  
        }catch(SQLException ex){

            JOptionPane.showMessageDialog(null,"eror  "+ex  );

        }
        
    }//GEN-LAST:event_butIniciarMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      
      
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JButton butIniciar;
    private javax.swing.JButton butRegistar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
