/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.Usuario;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import logica.Conexion;
import logica.ReguladorUsuario;
import logica.Univerzoom;

/**
 *
 * @author Gaia F. Braccia
 */
public class VentanaRegistro extends javax.swing.JFrame {
    Usuario u= VentanaInicioSesion.getU();
    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        butLimpiar = new javax.swing.JButton();
        butConfirmarRegistro = new javax.swing.JButton();
        butVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Univerzoom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 330, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrarse");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 140, 40));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 30));
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 340, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 190, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 30));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 30));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 170, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellidos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, 30));
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 150, -1));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 230, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, 30));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 30));

        butLimpiar.setBackground(new java.awt.Color(0, 0, 51));
        butLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        butLimpiar.setText("Limpiar");
        butLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(butLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 375, 110, 30));

        butConfirmarRegistro.setBackground(new java.awt.Color(0, 0, 51));
        butConfirmarRegistro.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butConfirmarRegistro.setForeground(new java.awt.Color(255, 255, 255));
        butConfirmarRegistro.setText("Registrarse");
        butConfirmarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butConfirmarRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(butConfirmarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 335, 110, 30));

        butVolver.setBackground(new java.awt.Color(0, 0, 51));
        butVolver.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        butVolver.setForeground(new java.awt.Color(255, 255, 255));
        butVolver.setText("Volver");
        butVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVolverActionPerformed(evt);
            }
        });
        jPanel1.add(butVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -7, 490, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void butConfirmarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butConfirmarRegistroActionPerformed
        // TODO add your handling code here:
        
        Conexion men1 = new Conexion();
         Conexion con = new Conexion();
        
         String usuario=txtUsuario.getText();
        String nombre=txtNombre.getText();
        String apellido=txtApellido.getText();
        int edad= (int) jSpinner1.getValue();
        String corre = txtCorreo.getText();
        String contraseña = txtContraseña.getText();
        boolean b=true; 
       
        if(txtUsuario.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() ||
            (int) jSpinner1.getValue() <=0 && txtCorreo.getText().isEmpty() || txtContraseña.getText().isEmpty() ){
            JOptionPane.showMessageDialog( this, " Tiene que llenar todos los campos","Error",JOptionPane.ERROR_MESSAGE); 
            b=false;
        }
        String correo= txtCorreo.getText();
       if (!ReguladorUsuario.esCorreo(correo)){
           JOptionPane.showMessageDialog( this, "Ingrese un correo valido","Error",JOptionPane.ERROR_MESSAGE); 
           b=false;
        }
       String user=txtUsuario.getText();
       if (!ReguladorUsuario.validar(usuario)){
           
          b=false;
        }
       String cont=txtContraseña.getText();
       if(cont.length()<6 ){
          JOptionPane.showMessageDialog( this, "La contraseña debe tener minimo 6 caracteres","Error",JOptionPane.ERROR_MESSAGE);
          b=false;
        }
            System.out.println(b);
        if(b){
       
             u= new Usuario(txtUsuario.getText(), txtNombre.getText(),txtApellido.getText(),
                (int) jSpinner1.getValue(),txtCorreo.getText() , txtContraseña.getText());
         usuario=txtUsuario.getText();
         nombre=txtNombre.getText();
         apellido=txtApellido.getText();
         edad= (int) jSpinner1.getValue();
         corre = txtCorreo.getText();
         contraseña = txtContraseña.getText();
        
        try{
            Statement comando=con.getConnection().createStatement();

           comando.executeUpdate("insert into usuarios(nombre,apellidos,correo,edad,usuario,contraseña) values('"+nombre+"','"+apellido+"','"+correo+"','"+edad+"','"+usuario+"','"+contraseña+"')");   
        }catch(SQLException ex){

            JOptionPane.showMessageDialog(null,"eror  "+ex  );

        }
   
        JOptionPane.showMessageDialog(this, " Usuario creado exitosamente");
        VentanaInicioSesion men= new VentanaInicioSesion();
        dispose();
        men.setVisible(true);
        }
    }//GEN-LAST:event_butConfirmarRegistroActionPerformed
    
   
    
    private void butLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butLimpiarActionPerformed
             // TODO add your handling code here:
             txtUsuario.setText("");
             txtApellido.setText("");
             txtContraseña.setText("");
             txtCorreo.setText("");
             txtNombre.setText("");
    }//GEN-LAST:event_butLimpiarActionPerformed

    private void butVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVolverActionPerformed
        // TODO add your handling code here:
         VentanaInicioSesion ven= new VentanaInicioSesion();
        
        ven.setVisible(true);
        dispose();
    }//GEN-LAST:event_butVolverActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
       if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
       if((c<'a'||c>'z')&&(c<'A'||c>'Z')&&(c<' '||c>' '))evt.consume();
    }//GEN-LAST:event_txtApellidoKeyTyped

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butConfirmarRegistro;
    private javax.swing.JButton butLimpiar;
    private javax.swing.JButton butVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
